config/routes.rb
Rails.application.routes.draw do
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :applications do
    resources :notes
  end

  root 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many   :notes, dependent: :destroy
  validates  :company, :position, presence: true
  
  scope :theirs, lambda { |id| where('user_id = ?' , id) }
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :applications, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected

    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to login_url
      end
    end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  
  def index
    @applications = Application.theirs(session[:user_id]).order(created_at: :desc)
  end
  
  def show
    @application = Application.find_by(id: params[:id], user_id: session[:user_id])
    if @application.nil?
      redirect_to applications_path, notice: 'No such record.'
    end
  end
  
  def new
  end
  
  def create
    @application = Application.new(application_params)
    @application.user_id = session[:user_id]
    
    @application.save
    respond_to do |format|
      format.html { redirect_to @application }
      format.js
    end
  end
  
  def edit
    @application = Application.find(params[:id])
  end
  
  def update
    @application = Application.find(params[:id])
 
    if @application.update(application_params)
      redirect_to @application
    else
      render 'edit'
    end
  end
  
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    redirect_to applications_path
  end

  private
    def application_params
      params.require(:application).permit(:company, :position, :applied_on, :refer, :found_on, :user_id, :got_job)
    end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @application = Application.find(params[:application_id])
    @note = @application.notes.create(note_params)
    redirect_to application_path(@application)
  end
  
  def destroy
    @application = Application.find(params[:application_id])
    @note = @application.notes.find(params[:id])
    @note.destroy
    redirect_to application_path(@application)
  end
 
  private
    def note_params
      params.require(:note).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_url(session[:user_id])
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:create, :new]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/_application.html.erb
<p>
 <%= link_to application.company, application_path(application) %> for 
 <%= application.position %> on 
 <%= application.applied_on %>
</p>

app/views/applications/_form.html.erb
<%= form_for :application, remote: true, url: applications_path, :html => {:id => "new_application"} do |f| %>
  <p>I applied at <%= f.text_field :company, :placeholder => "comapny name" %> for the <%= f.text_field :position, :placeholder => "position" %> position on <%= f.date_field :applied_on, :value => Time.now.strftime("%Y-%m-%d") %>.</p>
  <p>I heard about it from <%= f.text_field :refer, :placeholder => "someone" %> on <%= f.date_field :found_on, :value => Time.now.strftime("%Y-%m-%d") %>.</p>
  <div class="actions">
    <%= f.submit "Add New Application" %>
  </div>
<% end %>

app/views/applications/create.js.erb
$('#new_application').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@application) %>');

app/views/applications/edit.html.erb
<section id="jobform">
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>

	<%= form_for :application, url: application_path(@application), method: :patch do |f| %>
	  <p>I applied at <%= f.text_field :company, :placeholder => "comapny name" %> for the <%= f.text_field :position, :placeholder => "position" %> position on <%= f.date_field :applied_on, :value => Time.now.strftime("%Y-%m-%d") %>.</p>
	  <p>I heard about it from <%= f.text_field :refer, :placeholder => "someone" %> on <%= f.date_field :found_on, :value => Time.now.strftime("%Y-%m-%d") %>.</p>
	  <p>
	    <%= f.check_box :got_job %>
	    <%= f.label :got_job %>
	  </p>
	  <div class="actions">
	    <%= f.submit "Update Application" %>
	  </div>
	<% end %>
</section>

app/views/applications/index.html.erb
<p><%= link_to 'New application', new_application_path, id: "new_link", remote: true %></p>
<h1>Open Applications</h1>
<div id="incomplete_tasks">
   <%= render @applications %>
</div>

app/views/applications/new.html.erb
<h1>New Application</h1>

<section id="jobform">
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>

	<%= render :partial => 'form' %>

</section>

app/views/applications/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/applications/show.html.erb
<p>
  I applied at 
  <strong><%= @application.company %></strong> 
  for the <strong><%= @application.position %></strong> position on
  <strong><%= @application.applied_on %></strong>
</p>
<% unless @application.refer.empty? %>
<p>
  I heard about it from 
  <strong><%= @application.refer %></strong> on
  <strong><%= @application.found_on %></strong>.
</p>
<% end %>

<p><%= @application.got_job %></p>

<p><%= link_to 'Edit', edit_application_path(@application) %></p>
<p><%= link_to 'Destroy', application_path(@application), method: :delete, data: { confirm: 'Are you sure?' } %></p>

<h2>Notes</h2>
<% @application.notes.each do |note| %>
  <p>
    <%= note.body %>
	  <%= link_to 'Delete', [note.application, note],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>

<%= form_for([@application, @application.notes.build]) do |f| %>
  <p>
    <%= f.label :body, 'Add Note' %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Applied For</title>
  <meta name="viewport" content="width=device-width" />
  <meta name="apple-mobile-web-app-title" content="Applied For">
  <link rel="shortcut icon" href="/touch-icon.png">
  <link rel="apple-touch-icon-precomposed" href="/touch-icon.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    # (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    # (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    # m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    # })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    # 
    # ga('create', 'UA-49466821-1', 'applied-for.herokuapp.com');
    # ga('send', 'pageview');
  </script>
</head>
<body>
  <header>
  	<% if session[:user_id] %>
  		<%= button_to 'Logout', logout_path, method: :delete   %>
  		<% unless controller_name == 'applications' && action_name == 'index' %>
    		<%= link_to "home", applications_path %>
  		<% end %>
  	<% end %>
	</header>
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
	  <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

app/views/welcome/index.html.erb
<h1>Applied For</h1>
<p>An easy way to track where you have applied for a job.</p>

<p>Create <%= link_to "an Account", new_user_path %> to start tracking today.</p>

<p>Already have an account? <%= link_to "Log In.", login_path %></p>